name: 'GLL Test Action'
description: 'Ultra simple test version'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  before-release-hook:
    description: 'Before release hook path'
    required: false
    default: './.github/actions/before-release'

outputs:
  status:
    description: 'Status'
    value: 'success'

runs:
  using: 'composite'
  steps:
    - name: Simple test
      shell: bash
      run: |
        echo "🚀 Simple test of centralized action"
        echo "Hook path: ${{ inputs.before-release-hook }}"
        
    - name: Check hook exists
      shell: bash
      run: |
        if [ -f "${{ inputs.before-release-hook }}/action.yml" ]; then
          echo "✅ Hook found!"
        else
          echo "❌ Hook not found"
        fi
