name: 'GLL Kubernetes Deployment Action'
description: 'Centralized deployment action with hooks'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  before-release-hook:
    description: 'Before release hook path'
    required: false
    default: './.github/actions/before-release'
  before-deployment-hook:
    description: 'Before deployment hook path'
    required: false
    default: './.github/actions/before-deployment'
  after-deployment-hook:
    description: 'After deployment hook path'
    required: false
    default: './.github/actions/after-deployment'

outputs:
  deployment-status:
    description: 'Deployment status'
    value: ${{ steps.deploy.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Start deployment process
      shell: bash
      run: |
        echo "🚀 Starting GLL Deployment Pipeline"
        
    - name: Run before-release hook
      shell: bash
      run: |
        HOOK_PATH="${{ inputs.before-release-hook }}"
        if [ -f "$HOOK_PATH/action.yml" ]; then
          echo "✅ Found before-release hook at $HOOK_PATH"
          echo "🎯 Running before-release validations..."
          if [ -f "$HOOK_PATH/run.sh" ]; then
            chmod +x "$HOOK_PATH/run.sh"
            "$HOOK_PATH/run.sh" "v2.0.0-test" "sandbox"
          else
            echo "   Running pre-release validations..."
            sleep 1
            echo "   ✅ Pre-release validations completed!"
          fi
        else
          echo "ℹ️ No before-release hook at $HOOK_PATH"
        fi
    
    - name: Run before-deployment hook  
      shell: bash
      run: |
        HOOK_PATH="${{ inputs.before-deployment-hook }}"
        if [ -f "$HOOK_PATH/action.yml" ]; then
          echo "✅ Found before-deployment hook at $HOOK_PATH"
          echo "🚢 Running before-deployment preparations..."
          if [ -f "$HOOK_PATH/run.sh" ]; then
            chmod +x "$HOOK_PATH/run.sh"
            "$HOOK_PATH/run.sh" "v2.0.0-test" "sandbox"
          else
            echo "   Preparing deployment environment..."
            sleep 1
            echo "   ✅ Deployment preparation completed!"
          fi
        else
          echo "ℹ️ No before-deployment hook at $HOOK_PATH"
        fi
    
    - name: Simulate deployment
      id: deploy
      shell: bash
      run: |
        echo "🚢 Deploying to sandbox environment..."
        sleep 2
        echo "✅ Deployment completed successfully!"
        echo "status=success" >> $GITHUB_OUTPUT
    
    - name: Run after-deployment hook
      shell: bash
      run: |
        HOOK_PATH="${{ inputs.after-deployment-hook }}"
        if [ -f "$HOOK_PATH/action.yml" ]; then
          echo "✅ Found after-deployment hook at $HOOK_PATH"
          echo "🎉 Running after-deployment tests..."
          if [ -f "$HOOK_PATH/run.sh" ]; then
            chmod +x "$HOOK_PATH/run.sh"
            "$HOOK_PATH/run.sh" "v2.0.0-test" "sandbox" "https://sandbox.example.com"
          else
            echo "   Running post-deployment tests..."
            sleep 2
            echo "   ✅ Post-deployment tests passed!"
          fi
        else
          echo "ℹ️ No after-deployment hook at $HOOK_PATH"
        fi

    - name: Deployment summary
      shell: bash
      run: |
        echo "📋 Deployment Summary:"
        echo "   Status: success"
        echo "   Environment: sandbox" 
        echo "   Release: v2.0.0-test"
