name: 'GLL Kubernetes Deployment Action'
description: 'Minimal test version for validation'
author: 'GLL Sistemas'

inputs:
  deployment-config-path:
    description: 'Path to deployment configuration file'
    required: false
    default: 'deploy/deployment-config.yml'
  
  github-token:
    description: 'GitHub token for API access'
    required: true
  
  before-release-hook:
    description: 'Path to before-release hook action'
    required: false
    default: './.github/actions/before-release'
  
  before-deployment-hook:
    description: 'Path to before-deployment hook action'
    required: false
    default: './.github/actions/before-deployment'
  
  after-deployment-hook:
    description: 'Path to after-deployment hook action'
    required: false
    default: './.github/actions/after-deployment'

outputs:
  deployment-status:
    description: 'Final deployment status'
    value: ${{ steps.simulate.outputs.status }}
  
  environment:
    description: 'Target environment'
    value: 'sandbox'

runs:
  using: 'composite'
  steps:
    - name: Test Centralized Action
      shell: bash
      run: |
        echo "🚀 Testing Centralized Action"
        echo "Config: ${{ inputs.deployment-config-path }}"
        
    - name: Check before-release hook
      id: check-before-release
      shell: bash
      run: |
        if [ -f "${{ inputs.before-release-hook }}/action.yml" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "✅ Found before-release hook at ${{ inputs.before-release-hook }}"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "ℹ️ No before-release hook found"
        fi
    
    - name: Run before-release hook
      if: steps.check-before-release.outputs.exists == 'true'
      uses: ${{ inputs.before-release-hook }}
      with:
        release: "v2.0.0-test"
        environment: "sandbox"
        secrets-as-json: "{}"
    
    - name: Check before-deployment hook
      id: check-before-deployment
      shell: bash
      run: |
        if [ -f "${{ inputs.before-deployment-hook }}/action.yml" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "✅ Found before-deployment hook at ${{ inputs.before-deployment-hook }}"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "ℹ️ No before-deployment hook found"
        fi
    
    - name: Run before-deployment hook
      if: steps.check-before-deployment.outputs.exists == 'true'
      uses: ${{ inputs.before-deployment-hook }}
      with:
        release: "v2.0.0-test"
        environment: "sandbox"
        secrets-as-json: "{}"
    
    - name: Simulate deployment
      id: simulate
      shell: bash
      run: |
        echo "🚢 [FAKE] Deploying to sandbox environment..."
        sleep 2
        echo "✅ [FAKE] Deployment successful!"
        echo "status=success" >> $GITHUB_OUTPUT
    
    - name: Check after-deployment hook
      id: check-after-deployment
      shell: bash
      run: |
        if [ -f "${{ inputs.after-deployment-hook }}/action.yml" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "✅ Found after-deployment hook at ${{ inputs.after-deployment-hook }}"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "ℹ️ No after-deployment hook found"
        fi
    
    - name: Run after-deployment hook
      if: steps.check-after-deployment.outputs.exists == 'true'
      uses: ${{ inputs.after-deployment-hook }}
      with:
        release: "v2.0.0-test"
        environment: "sandbox"
        deployment-url: "https://sandbox.test.local"
        secrets-as-json: "{}"

branding:
  icon: 'rocket'
  color: 'blue'
